const express = require('express')
const path = require('path')
const router = require('./route/mymodule')
const app = express()
const cookieParser = require('cookie-parser')
const session = require('express-session')

app.use(express.urlencoded({extended:false}))
app.use(cookieParser())
app.use(session({secret:"mysession",resave:false,saveUninitialized:false}))
app.use(router)
app.set('views',path.join(__dirname,'/views'))
app.set('view engine','ejs')
app.use(express.static(path.join(__dirname,'/public')))

app.listen(3000,()=>console.log("start server"))